services:
  - type: web
    name: leetcode-analytics
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: postgresql://leetcode_v8js_user:zIvqJDcONbVPyFULUyvirmwuwGeGZmfd@dpg-d378abre5dus7394eiog-a/leetcode_v8js
      - key: EMAIL_USER
        value: sanatanisofindia@gmail.com
      - key: EMAIL_PASS
        value: wxgg guhe ohhu ljho